name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write # Required for GitHub Pages deployment

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4 # Updated to latest version

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Ensures a stable environment

      - name: Install dependencies
        run: npm ci # More reliable than npm install

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4 # Updated to v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4 # Updated to latest version

      - name: Download artifact
        uses: actions/download-artifact@v4 # Updated to v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages # Ensures deployment to the correct branch
